#!/usr/bin/env python3
"""
Aggregate summary.json / reinforce_run_*.json into four markdown tables (DQN, PPO, A2C, REINFORCE).

Run from project root:
    python analysis/export_hyperparameter_tables.py

Writes: results/hyperparameter_tables.md
"""

from __future__ import annotations

import glob
import json
import os
import sys
from typing import Any, Dict, List

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

OUT = os.path.join(ROOT, "results", "hyperparameter_tables.md")


def _md_table(headers: List[str], rows: List[List[Any]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for r in rows:
        lines.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(lines)


def _load_json(path: str) -> Dict[str, Any]:
    with open(path) as f:
        return json.load(f)


def _flatten_cfg(cfg: Dict[str, Any]) -> List[str]:
    keys = sorted(cfg.keys())
    return keys + [str(cfg[k]) for k in keys]


def build_dqn_table() -> str:
    paths = sorted(glob.glob(os.path.join(ROOT, "models", "dqn", "run_*", "summary.json")))
    if not paths:
        return "_No DQN summaries found (run training/dqn_training.py)._"
    cfgs = [_load_json(p)["cfg"] for p in paths]
    all_keys = sorted({k for c in cfgs for k in c.keys()})
    headers = ["run_id"] + all_keys + ["mean_eval"]
    rows: List[List[Any]] = []
    for i, p in enumerate(paths):
        d = _load_json(p)
        row = [i] + [d["cfg"].get(k, "") for k in all_keys] + [d.get("mean_eval", "")]
        rows.append(row)
    return _md_table(headers, rows)


def build_sb3_pg_table(algo: str) -> str:
    sub = "ppo" if algo == "PPO" else "a2c"
    paths = sorted(glob.glob(os.path.join(ROOT, "models", "pg", sub, "run_*", "summary.json")))
    if not paths:
        return f"_{algo} summaries not found (run training/pg_training.py --algo {sub})._"
    cfgs = [_load_json(p)["cfg"] for p in paths]
    all_keys = sorted({k for c in cfgs for k in c.keys()})
    headers = ["run_id"] + all_keys + ["mean_eval"]
    rows: List[List[Any]] = []
    for i, p in enumerate(paths):
        d = _load_json(p)
        row = [i] + [d["cfg"].get(k, "") for k in all_keys] + [d.get("mean_eval", "")]
        rows.append(row)
    return _md_table(headers, rows)


def build_reinforce_table() -> str:
    paths = sorted(glob.glob(os.path.join(ROOT, "models", "pg", "reinforce_run_*.json")))
    if not paths:
        return "_REINFORCE summaries not found (run training/reinforce_training.py)._"
    cfgs = [_load_json(p)["cfg"] for p in paths]
    all_keys = sorted({k for c in cfgs for k in c.keys()})
    headers = ["run_id"] + all_keys + ["mean_return_last_50", "mean_entropy_last_50"]
    rows: List[List[Any]] = []
    for i, p in enumerate(paths):
        d = _load_json(p)
        row = (
            [i]
            + [d["cfg"].get(k, "") for k in all_keys]
            + [d.get("mean_return_last_50", ""), d.get("mean_entropy_last_50", "")]
        )
        rows.append(row)
    return _md_table(headers, rows)


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    parts = [
        "# Hyperparameter experiment tables\n",
        "Generated by `analysis/export_hyperparameter_tables.py`.\n",
        "## DQN\n",
        build_dqn_table(),
        "\n\n## PPO\n",
        build_sb3_pg_table("PPO"),
        "\n\n## A2C\n",
        build_sb3_pg_table("A2C"),
        "\n\n## REINFORCE\n",
        build_reinforce_table(),
        "\n",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    print("Wrote", OUT)


if __name__ == "__main__":
    main()
